### ISSUE TITLE
Add HTTP interface

### ISSUE THREAD

**Issue by ghost** [weatherforce/chercheville#8]
Also get rid of this warning:
```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.1) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.1) lib/supervisor.ex:556: Supervisor.start_link/2
  (stdlib 3.11.2) supervisor.erl:379: :supervisor.do_start_child_i/3
  (stdlib 3.11.2) supervisor.erl:365: :supervisor.do_start_child/2
  (stdlib 3.11.2) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
```

**Comment by ghost** [comment]
Done and merged to master.
